<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="four_wheel_robot">

    <!-- 包含文件 -->
    <xacro:include filename="$(find four_wheel_robot_description)/urdf/robot_core.xacro"/>
    <xacro:include filename="$(find four_wheel_robot_description)/urdf/sensors.xacro"/>

    <!-- 添加3D激光雷达 -->
    <xacro:lidar_3d_sensor 
        name="laser_link" 
        parent="base_link" 
        xyz="0.2 0 ${chassis_height}" 
        rpy="0 0 0"/>
                          
    <!-- 添加摄像头 -->
    <xacro:stereo_camera_sensor name="stereo_camera" 
                               parent="base_link" 
                               xyz="${chassis_length/2} 0 ${chassis_height/2}" 
                               rpy="0 0 0"
                               baseline="0.12"/>
                               
    <!-- 添加IMU -->    
    <xacro:imu_sensor name="imu" parent="base_link" xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>

</robot>