<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- 机器人参数 -->
    <xacro:property name="chassis_length" value="0.6"/>
    <xacro:property name="chassis_width" value="0.4"/>
    <xacro:property name="chassis_height" value="0.2"/>
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_width" value="0.05"/>
    <xacro:property name="wheel_pos_x" value="0.25"/>  <!-- 前后轮距离车体中心的距离 -->
    
    <!-- 材质定义 -->
    <material name="blue">
        <color rgba="0 0 0.8 1"/>
    </material>
    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <!-- Base Footprint -->
    <link name="base_footprint">
        <inertial>
            <mass value="0.0001"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia 
                ixx="0.0001" ixy="0.0" ixz="0.0"
                iyy="0.0001" iyz="0.0"
                izz="0.0001"/>
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.001 0.001 0.001"/>
            </geometry>
        </collision>
    </link>

    <!-- base_link 到 base_footprint 的固定关节 -->
    <joint name="base_link_to_footprint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 -${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <!-- 底盘 Base Link -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="blue"/>
            <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
        </visual>
        <collision>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
        </collision>
        <inertial>
            <mass value="5.0"/>
            <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
            <inertia 
                ixx="${(1/12) * 5.0 * (chassis_width*chassis_width + chassis_height*chassis_height)}" 
                ixy="0" 
                ixz="0"
                iyy="${(1/12) * 5.0 * (chassis_length*chassis_length + chassis_height*chassis_height)}" 
                iyz="0"
                izz="${(1/12) * 5.0 * (chassis_length*chassis_length + chassis_width*chassis_width)}"/>
        </inertial>
    </link>
    

    <!-- 车轮宏定义 -->
    <xacro:macro name="wheel" params="prefix x_offset y_offset">
        <!-- 轮子link -->
        <link name="${prefix}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="black"/>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            </collision>
            <inertial>
                <mass value="0.5"/>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <inertia 
                    ixx="${(1/12) * 0.5 * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
                    ixy="0" 
                    ixz="0"
                    iyy="${(1/12) * 0.5 * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
                    iyz="0"
                    izz="${(1/2) * 0.5 * (wheel_radius*wheel_radius)}"/>
            </inertial>
        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel"/>
            <origin xyz="${x_offset} ${y_offset} 0" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>

        <!-- Gazebo specific wheel properties -->
        <gazebo reference="${prefix}_wheel">
            <material>Gazebo/Black</material>
            <mu1>0.8</mu1>
            <mu2>0.8</mu2>
            <kp>500000.0</kp>
            <kd>50.0</kd>
            <minDepth>0.001</minDepth>
            <maxVel>1.5</maxVel>
            <fdir1>1 0 0</fdir1>
        </gazebo>

        <!-- 添加传动装置 -->
        <transmission name="${prefix}_wheel_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_wheel_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_wheel_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>

    <!-- 使用wheel_pos_x参数统一轮子位置 -->
    <xacro:wheel prefix="front_left" x_offset="${wheel_pos_x}" y_offset="${chassis_width/2 + wheel_width/2}"/>
    <xacro:wheel prefix="front_right" x_offset="${wheel_pos_x}" y_offset="-${chassis_width/2 + wheel_width/2}"/>
    <xacro:wheel prefix="rear_left" x_offset="-${wheel_pos_x}" y_offset="${chassis_width/2 + wheel_width/2}"/>
    <xacro:wheel prefix="rear_right" x_offset="-${wheel_pos_x}" y_offset="-${chassis_width/2 + wheel_width/2}"/>

    <gazebo reference="base_link">
        <material>Gazebo/Blue</material>
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
        <kp>1000000.0</kp>
        <kd>100.0</kd>
    </gazebo>

    <!-- 差速驱动插件配置 -->
    <gazebo>
        <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
            <!-- 基本配置 -->
            <ros>
                <namespace>/</namespace>
                <remapping>cmd_vel:=cmd_vel</remapping>
                <remapping>odom:=odom</remapping>
            </ros>

            <!-- 轮子配置 -->
            <left_joint>front_left_wheel_joint</left_joint>
            <right_joint>front_right_wheel_joint</right_joint>
            <wheel_separation>0.4</wheel_separation>
            <wheel_diameter>0.2</wheel_diameter>

            <!-- 发布TF和里程计 -->
            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>

            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_link</robot_base_frame>
        </plugin>
    </gazebo>

</robot>